[options]
# Ubicación del almacenamiento de archivos de Odoo. Aquí Odoo guarda sesiones y adjuntos
# !!! IMPORTANTE !!!
# El usuario de Odoo desde el interior del contenedor DEBE tener permisos de escritura en este directorio (chmod)
data_dir = /var/lib/odoo

# Host de Postgres
# Si estás usando Postgres local, db_host será 'host.docker.internal'
# Consulta este enlace para más detalles
# https://stackoverflow.com/questions/31324981/how-to-access-host-port-from-docker-container
db_host = db
db_user = odoo
db_password = odoo
db_port = 5432

# Contraseña para el Administrador de la Base de Datos de Odoo
admin_passwd = admin123

# Aquí Odoo buscará complementos
# El código fuente de Odoo está ubicado en /home/odoo/odoo
# El código fuente de Odoo EE está ubicado en /home/odoo/enterprise
# Aquí hay algunos ejemplos de rutas
addons_path = /home/bo/odoo/addons,
	/home/bo/odoo/odoo/addons,
	/home/bo/enterprise,
	/home/bo/extra-addons/odoo_addons_extra,
	/home/bo/extra-addons/odoo_l10n_ar,
	/home/bo/extra-addons/odoo_l10n_ar/odoo_l10n,
	/home/bo/extra-addons/odoo_addons_others

# ***********************
# **** Opciones adicionales
# ***********************
# db_maxconn = 64
# db_name = False
# db_sslmode = prefer
# db_template = template0
# dbfilter = 
# demo = {}
# email_from = False
# geoip_database = /usr/share/GeoIP/GeoLite2-City.mmdb
# http_enable = True
# http_interface = 
# http_port = 8071
# import_partial = 
# limit_memory_hard = 2684354560
# limit_memory_soft = 2157483648
# limit_request = 8192
limit_time_cpu = 720
limit_time_real = 1440
# limit_time_real_cron = -1
# list_db = True
# log_db = False
# log_db_level = warning
# log_handler = :INFO
# log_level = info
# logfile = 
# longpolling_port = 8072
# max_cron_threads = 2
# osv_memory_age_limit = False
# osv_memory_count_limit = False
# pg_path = 
# pidfile = 
# proxy_mode = False
# reportgz = False
# screencasts = 
# screenshots = /tmp/odoo_tests
# server_wide_modules = base,web
# smtp_password = False
# smtp_port = 25
# smtp_server = localhost
# smtp_ssl = False
# smtp_user = False
# syslog = False
# test_enable = False
# test_file = 
# test_tags = None
# transient_age_limit = 1.0
# translate_modules = ['all']
# unaccent = False
# upgrade_path = 
# without_demo = False
# workers = 0

